### ISSUE TITLE
Let's talk on a call instead of github

### ISSUE THREAD

**Issue by mixmix** [ssb-js/ssb-js#14]
I'm starting to see chaffed by these issues and PRs ... I guess it's the opening phase and no avoiding it.
But I would personally rather see some faces and hear voices to ground this conversation.

We can talk about some details sure, but I just wanna talk about how people are and what they care about. We can always continue thread here.

**Comment by soapdog** [comment]
I'd love to hop onto a call.

(cue, I am writing a book about how to manage effective online calls and meetups rsrsrs)

**Comment by christianbundy** [comment]
What TZ are we all in? Here's my latest memory:

```sh
printf 'staltz         | '; TZ="Europe/Helsinki" date
printf 'arj03          | '; TZ="Europe/Copenhagen" date
printf 'soapdog        | '; TZ="Europe/London" date
printf 'christianbundy | '; TZ="America/Los_Angeles" date
printf 'mixmix         | '; TZ="Pacific/Auckland" date
```

I popped those into WorldTimeBuddy (free account limit, left out Copenhagen but it's between Helsinki and London) and it looks like this: https://www.worldtimebuddy.com/?pl=1&lid=658225,2643743,5368361,2193733&h=658225

There's only one sliver of overlap, but it doesn't look like very much fun for Mix: https://www.worldtimebuddy.com/?qm=1&lid=658225,2643743,5368361,2193733&h=658225&date=2020-9-2&sln=21-22

**Comment by soapdog** [comment]
friends, my time is quite flexible and I usually can't sleep anyway. So I can be in the call in whatever time is best for you all.

**Comment by soapdog** [comment]
Bump! How do you feel about this folks?

**Comment by christianbundy** [comment]
I think someone just needs to propose a time.

Soonest time that works for me: tomorrow (Friday, Oct 2) at 13:00 my time ([link](https://www.worldtimebuddy.com/?qm=1&lid=658225,2643743,5368361,2193733&h=658225&date=2020-10-1&sln=23-24)). This looks super crappy for @staltz though.

I'll be in https://meet.jit.si/ssb-js

I was going to make a cheeky comment about how we could use that 'golden ratio' meeting script I wrote:

```javascript
const goldenRatio = (1 + Math.sqrt(5))/2
const dayDuration = 1000 * 86400
const timeBetween = goldenRatio * dayDuration

const nth = (n) => new Date(n * timeBetween)
const next = () => nth(Math.ceil(Date.now() / timeBetween))
```

...but, uhh...

```javascript
next() // => Fri Oct 02 2020 12:34:11 GMT-0700 (Pacific Daylight Time)
```

This is a *very* weird coincidence.

---

<details><summary>New canonical script that rounds to the hour because wtf</summary>

```javascript
const second = 1000;
const minute = second * 60;
const hour = minute * 60;
const day = hour * 24;
const goldenRatio = (1 + Math.sqrt(5)) / 2;

const interval = goldenRatio * day;
const roundToHour = (t) => Math.round(t / hour) * hour;
const nth = (n) => new Date(roundToHour(n * interval));
const next = () => nth(Math.ceil(Date.now() / interval));

next(); // => Fri Oct 02 2020 13:00:00 GMT-0700 (Pacific Daylight Time)
```
</details>

**Comment by christianbundy** [comment]
swing and a miss

**Comment by christianbundy** [comment]
Because 13:00 on Fridays works well for me, here's another one foretold by the magical golden ratio meeting scheduler:

Fri Oct 23 2020 13:00:00 GMT-0700 (Pacific Daylight Time)

**Comment by mixmix** [comment]
Sorry only saw this now.  organising international meetings for the next day is risky biz

Keen to meet, October 23 is like 3 weeks away. Feels long. How about 1-2 weeks away

**Comment by arj03** [comment]
Been away for a SSB pointer grant kickoff event. Fri Oct 23 2020 13:00:00 GMT-0700 (Pacific Daylight Time) works well for me. I'm away most of next week on vacation.

**Comment by mixmix** [comment]
Okay, someone want to send a calendar invite out?

**Comment by arj03** [comment]
Reminder, this meeting happens in roughly 2 days. @ssb-js

**Comment by soapdog** [comment]
The call happened, we had fun, I'll schedule the next call in a new issue.
