### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by christianbundy** [ssb-js/ssb-js#25]
This is one of my least favorite conversations on the planet, but I think we should have it once in one place instead of having the same conversations in bits and pieces all over the modules. **What are the minimum 'code style' standards that we want to enforce?** Here are my preferences:

- I'd prefer to use popular convention instead of inventing our own.
- I'd prefer to use boring conventions so that our code is familiar and predictable.
- I'd prefer to separate concerns so that our formatting (syntax) and logic (semantics) can be changed independently.

I'd suggest:

- **[ESLint:Recommended](https://eslint.org/docs/rules/)** for semantics -- Most/all modern linters use ESLint under the hood, and all of the most common + boring + uncontroversial rules have been added to a 'recommended' ruleset that comes with ESLint. This is the smallest and most agreeable ruleset I'm aware of, and applying it to our modules has been quick and easy.
- **[Prettier](https://prettier.io/)** for syntax -- 41 times more npm downloads than StandardJS, 18x more GitHub dependents, formats dozens of languages (Markdown, JS-in-Markdown (!), CSS, GraphQL, etc), and produces an uncontroversial style that's boring and familiar enough for everyone.

I was originally thinking that maintainers could just use their own code style, but I doubt that we want to change code style every 6 months or whatever, so maybe we should just have a default code style so that we can decide on and then move on to actually-interesting problems. Anyone have any big blocking concerns about ESLint + Prettier, or suggestions for more-boring style guides? My goal is to hit the sweet point between 'useless' and 'controversial'.

**Comment by staltz** [comment]
ESLint:Recommended :+1:, Prettier (default configs) :+1:

**Comment by staltz** [comment]
Some additional guidelines would have to be done for TypeScript. There is [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md) but also TypeScript comes with its own "compiler rules" in the config files, we'd have to come up with a reasonable convention for that.
