### ISSUE TITLE
Merge commits disabled?

### ISSUE THREAD

**Issue by christianbundy** [ssb-js/ssb-js#28]
@staltz I went to merge your PRs in ssb-keys but it wouldn't let me -- it says that merge commits have been 'disabled for this repository'. Was that intentional? We don't have any rules against locking each other out of normal actions, but I'm surprised that I can't merge pull requests anymore.

![Screenshot_2020-09-23 Build software better, together](https://user-images.githubusercontent.com/537700/94082129-11eeec00-fdb5-11ea-9e00-253137530304.png)

**Comment by staltz** [comment]
@christianbundy You can "rebase and merge"! :)

Obviously you can change the setting if you want, but this way I'm trying to communicate the preferred settings for this repo.

**Comment by christianbundy** [comment]
:+1: :heart:
