### ISSUE TITLE
some people are owners, some people members

### ISSUE THREAD

**Issue by mixmix** [ssb-js/ssb-js#5]
in the ssb-js some people are owners and others members.
I assume that was a mistake?

**Comment by mixmix** [comment]
I can't assign this to anyone (I'm a lowly member) but if I could it would assign it to @christianbundy :japanese_goblin:

**Comment by staltz** [comment]
Done.

**Comment by mixmix** [comment]
<3

**Comment by christianbundy** [comment]
Thankf for fixing it!

History: You can't change the role of people you've invited until they've accepted the invite. Since Staltz and Soapdog had already accepted I fixed their member role but couldn't make Mix and Arj owners yet.
