### ISSUE TITLE
How and when to do releases

### ISSUE THREAD

**Issue by arj03** [ssb-js/ssb-js#8]
One of the things I liked about SSB in the beginning was that the main branch as always pushed to npm more or less after a merge. This meant that it was quite easy to get small changes in and pushed out quickly. It might also have been one of the problems that made so many PRs go stale, as nobody wanted to be the one pushing these changes to npm and thus face the consequence of what happens if the stuff doesn't work. Not sure.

I have noticed that some modules lately have started to accumulate changes that are not published.

What do people think? And should this be something for the ssb-js to take a stance on, or should it be left to the maintainer, it seems to me that with such a tight system of modules, it would make most sense to have 1 rule for the whole org?

**Comment by christianbundy** [comment]
My only strong preferences:

- PRs are merged quickly.
- Merged code doesn't go unreleased for 'too long' (maybe 30+ days?).

I like having code bake in the main branch for a while before releasing it to the public, *especially* when new features or breaking changes are involved. This gives you (and more importantly: other people!) the opportunity to try out the new code and suggest improvements before you commit to it with an official release.

**Comment by mixmix** [comment]
**I personally want the `master` / `main` branch to be _published on merge_.**
_or published very shortly after once a batch of merges have happened_

Reasons:
1. We don't have any process for tracking "publishing sometime later" so it's invisible 
1. When I merge + publish, I scoop up unpublished changes and can end up pushing bugs into production that I didn't write. sucks
2. It's nice if the landing page of a repo is the leading published state
3. Why is it in the main branch if it's not ready to be published?
    - if you're not sure it's safe, make a tag or branch and reference that in production to test it out a bit, _then merge + publish_
4. If you don't publish on merge, then there's a possibility you will forget

**Comment by arj03** [comment]
I agree with mix on this one.

About breaking changes, isn't that what the whole version scheme is for, so I don't think its that controversial. The only place where this can be a bit, is for something like ssb-server that doesn't really use the version numbers and that has caused problems in the pasts. There it would probably be better with something like release candidates. But I don't think that is a concern for now as we don't have that module in ssb-js (yet...).

**Comment by christianbundy** [comment]
Thanks for adding explanations, I'd be comfortable adding that to the governance document.

Implementation suggestion: "Projects without open pull requests SHOULD should be versioned and published."

:boom:

**Comment by soapdog** [comment]
It is ok to publish on merge but only if make sure to pay attention to semver. 

Should we consider LTS versions? I am asking because it alters how we think about making releases.

**Comment by arj03** [comment]
Sure, semver is very important, but it has always been important. I think making more releases means people will be more in the habit of doing releases, so hopefully that should make the whole ceremony of doing a released a lot easier.

Do you mean node LTS?

**Comment by mixmix** [comment]
I guess he means LTS like `secret-stack@14` is guarenteed to get all security patches (even though current version is 19 or something)

**Comment by arj03** [comment]
Fixed by #9
